name: Run Unit Tests

on:
    push:

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Python 3
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.11
            - name: Install dependencies
              run: pip install -U pip -r requirements.txt
            - name: run tests with unittest
              run: python -m unittest tests/test.py -v
